baseURL = "https://goofy-mclean-3dca53.netlify.app"
languageCode = "en-us"
theme = "sauna-landing"
title = "Clearlight Infrared Saunas | Portable Infrared Saunas for Home"
description = "Les saunas Clearlight Infrared aident à la désintoxication, à la perte de poids, etc. Trouvez un sauna infrarouge portable et sûr pour votre maison avec une garantie à vie. Explorez maintenant."
